Repository SaekKkanDa/OppaManyColorTone, pull requests merged in 2023-03, with the labels that each got.

#100 Feature: color.js 봄 데이터 수정
  src/data/color.js
  src/pages/ChoiceColor/index.jsx
  src/pages/ChoiceColor/style.jsx
Labels: feature

#101 [settings] eslint 환경 설정 수정
  .eslintrc
  .eslintrc.cjs
Labels: setting

#118 sentry 설정
  package.json
  src/main.tsx
  yarn.lock
Labels: setting

#122 refactor: alias path로 변경 및 firebase DB 모듈화
  package.json
  src/components/Spinner/ColorImgSpinner.tsx
  src/data/resultColorData.ts
  src/pages/ChoiceColor/index.tsx
  src/pages/FaceDetection/index.tsx
  src/pages/Landing/index.tsx
  src/pages/Result/index.tsx
  src/pages/WrongAccess/index.tsx
  src/utils/addNumberOfUsers.ts
  src/utils/omctDb.ts
  tsconfig.json
  vite.config.js
Labels: refactoring

#125 컬러 선택 로직 수정 및 보너스 단계 추가
  src/assets/icon/color-spinner.png
  src/components/LoadingIndicator/index.tsx
  src/components/LoadingIndicator/style.ts
  src/data/choiceColorData.ts
  src/data/resultColorData.ts
  src/hooks/useChoiceColor.ts
  src/pages/ChoiceColor/BasicStage/index.tsx
  src/pages/ChoiceColor/BasicStage/style.ts
  src/pages/ChoiceColor/BonusStage/index.tsx
  src/pages/ChoiceColor/BonusStage/style.ts
  src/pages/ChoiceColor/Guidance/index.tsx
  src/pages/ChoiceColor/Guidance/style.ts
  src/pages/ChoiceColor/index.tsx
  src/pages/ChoiceColor/style.tsx
  src/pages/Result/index.tsx
  src/utils/getBonusColorOptions.ts
Labels: feature
