Repository SaekKkanDa/OppaManyColorTone, pull requests merged in 2023-10, with the labels that each got.

#231 CLS 최적화: dvh로 변경 및 이미지, 폰트 최적화
  public/fonts/JalnanOTF00.woff
  src/components/Layout/MobileLayout.tsx
  src/components/LoadingIndicator/style.ts
  src/components/Spinner/ColorImgSpinner.tsx
  src/pages/_document.page.tsx
  src/pages/choice-color/BasicStage/style.ts
  src/pages/image-upload/style.ts
  src/pages/index.page.tsx
  src/pages/style.ts
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
Labels: feature, priority-high

#226 Feature/#211 multi language
  package-lock.json
  package.json
  public/translations/en.json
  public/translations/ko.json
  src/components/Button/RestartButton/index.tsx
  src/components/Layout/MobileLayout.tsx
  src/components/Tag/Tag.tsx
  src/data/resultColorData.ts
  src/pages/404/index.page.tsx
  src/pages/_app.page.tsx
  src/pages/all-types-view/index.page.tsx
  src/pages/all-types-view/style.ts
  src/pages/choice-color/BasicStage/index.tsx
  src/pages/choice-color/BonusStage/index.tsx
  src/pages/choice-color/Guidance/index.tsx
  src/pages/image-upload/FaceDetection/index.tsx
  src/pages/image-upload/index.page.tsx
  src/pages/index.page.tsx
  src/pages/result/PaletteSubpage/index.tsx
  src/pages/result/ShareSubPage/index.tsx
  src/pages/result/index.page.tsx
  src/recoil/app.ts
  src/utils/flattenMessages.ts
  tsconfig.json
  yarn.lock
Labels: priority-low

#235 alert창 커스텀
  public/translations/en.json
  public/translations/ko.json
  src/components/AlertModal/AlertModal.tsx
  src/pages/image-upload/FaceDetection/index.tsx
  src/pages/image-upload/index.page.tsx
  src/pages/result/index.page.tsx
  src/pages/result/share.logic.ts
  src/pages/result/share.subPage.tsx
  src/styles/theme.ts
  src/utils/clipboard.ts
Labels: feature

#236 스타일 컨벤션 적용 리팩토링
  src/components/ColorChipSpinner/index.tsx
  src/components/ColorChipSpinner/style.ts
  src/components/ErrorBoundary/index.tsx
  src/components/Layout/MobileLayout.tsx
  src/components/Palette/index.tsx
  src/components/Palette/style.ts
  src/components/Spinner/ColorImgSpinner.tsx
  src/components/Tag/index.tsx
  src/pages/404/index.page.tsx
  src/pages/404/style.ts
  src/pages/all-types-view/index.page.tsx
  src/pages/all-types-view/style.ts
  src/pages/choice-color/BasicStage/index.tsx
  src/pages/choice-color/BasicStage/style.ts
  src/pages/choice-color/BonusStage/index.tsx
  src/pages/choice-color/BonusStage/style.ts
  src/pages/choice-color/Guidance/index.tsx
  src/pages/choice-color/Guidance/style.ts
  src/pages/choice-color/index.page.tsx
  src/pages/choice-color/style.ts
  src/pages/image-upload/FaceDetection/index.tsx
  src/pages/image-upload/FaceDetection/style.ts
  src/pages/image-upload/index.page.tsx
  src/pages/image-upload/style.ts
  src/pages/index.page.tsx
  src/pages/result/RestartButton/index.tsx
  src/pages/result/index.page.tsx
  src/pages/result/palette.subPage.tsx
  src/pages/result/share.subPage.tsx
  src/pages/result/style.ts
  src/pages/style.ts
Labels: priority-mid, refactoring

#240 refactor(AlertModal): 모달 스타일 수정 및 props 변경
  public/translations/en.json
  public/translations/ko.json
  src/components/AlertModal/AlertModal.tsx
  src/components/AlertModal/index.tsx
  src/components/AlertModal/style.ts
  src/pages/all-types-view/style.ts
  src/pages/choice-color/Guidance/index.tsx
  src/pages/choice-color/Guidance/style.ts
  src/pages/choice-color/style.ts
  src/pages/image-upload/FaceDetection/index.tsx
  src/pages/image-upload/index.page.tsx
  src/pages/image-upload/style.ts
  src/pages/result/index.page.tsx
  src/pages/result/share.subPage.tsx
  src/pages/result/style.ts
  src/pages/style.ts
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
Labels: refactoring

#241 Alert 모달 스타일 수정 및 공유 기능 에러핸들링 보완
  public/translations/en.json
  public/translations/ko.json
  src/components/AlertModal/style.ts
  src/pages/result/share.subPage.tsx
Labels: bug
