Repository SaekKkanDa/OppaManyColorTone, pull requests merged in 2023-02, with the labels that each got.

#7 공통 스타일 세팅 (#5)
  index.html
  src/App.jsx
  src/styles/GlobalStyle.jsx
  src/styles/resetStyle.jsx
  src/styles/theme.jsx
Labels: setting

#8 파이어베이스 초기 셋팅 및 db 연동 확인 (#2)
  .firebaserc
  .gitignore
  database.rules.json
  firebase.json
  package.json
  src/firebase.js
  src/pages/Landing/index.jsx
  vite.config.js
  yarn.lock
Labels: setting

#14 메인페이지 마크업
  src/components/Layout/MobileLayout.jsx
  src/pages/Landing/index.jsx
Labels: feature

#28 #25 - 시작하기 버튼 클릭 시 사진 업로드 페이지 이동
  src/pages/Landing/index.jsx
  src/pages/Landing/style.jsx
Labels: feature

#30 메인 페이지 - 사용자 수 안내 기능 구현
  src/pages/Landing/index.jsx
Labels: feature

#31 choice-color 페이지 마크업 완료
  src/Router.jsx
  src/pages/ChoiceColor/index.jsx
  vite.config.js
Labels: feature

#33 메인 페이지 - 중앙 에니메이션 추가
  public/landingColor.png
  public/langinThink.png
  src/components/Spinner/ColorImgSpinner.jsx
  src/components/Spinner/ColorSpinner.jsx
  src/pages/Landing/index.jsx
  src/pages/Landing/style.jsx
Labels: feature

#37 이미지 크롭 작업
  package-lock.json
  package.json
  src/Router.jsx
  src/pages/FaceDetection/index.jsx
Labels: feature

#40 setup recoil
  package.json
  src/App.jsx
  src/pages/FaceDetection/index.jsx
  src/recoil/app.js
Labels: setting

#44 Feat: 최종결과값 출력 함수 작성
  src/constant/colorData.js
  src/data/colorPalette.js
  src/pages/ChoiceColor/index.jsx
Labels: feature

#51 styled 작업
  src/pages/FaceDetection/index.jsx
  src/pages/FaceDetection/style.jsx
Labels: feature

#58 모달 이미지 출력
  src/pages/FaceDetection/index.jsx
  src/pages/ImageUpload/index.jsx
  src/pages/ImageUpload/style.jsx
Labels: feature

#49 Feat: 최종 결과값 recoil에 저장
  src/pages/ChoiceColor/index.jsx
  src/pages/ChoiceColor/style.jsx
  src/recoil/app.js
Labels: feature

#62 Feat: 이미지 출력
  src/pages/ChoiceColor/index.jsx
  src/pages/ChoiceColor/style.jsx
Labels: feature

#80 Feat: userImg 초기화
  src/pages/ChoiceColor/index.jsx
Labels: feature, bug
