Repository SaekKkanDa/OppaManyColorTone, pull requests merged in 2024-06, with the labels that each got.

#252 랜딩페이지 UI 개선 (유저 숫자 증가 애니메이션 추가)
  src/hooks/useCountUp.ts
  src/pages/index.page.tsx
  src/pages/style.ts
  src/recoil/app.ts
Labels: feature, bug

#255 feat: google tag manager 연동
  src/pages/_document.page.tsx
Labels: feature

#256 GTM 배포 테스트
  src/pages/_document.page.tsx
Labels: feature

#257 GA4 + GTM 설치
  .nvmrc
  package-lock.json
  package.json
  src/pages/_app.page.tsx
  src/pages/_document.page.tsx
  src/utils/firebase.ts
  yarn.lock
Labels: feature

#258 GTM 배포 테스트
  .nvmrc
  package-lock.json
  package.json
  src/pages/_app.page.tsx
  src/pages/_document.page.tsx
  src/utils/firebase.ts
  yarn.lock
Labels: release
